version: "3.8"

services:
  app-dev:
    profiles: ["dev"]
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=http://libsql:8080
      - PORT=3000
      - HOST=0.0.0.0
    command: pnpm run dev
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
    networks:
      - app-network

  app:
    profiles: ["prod"]
    build:
      context: .
      target: production
    ports:
      - "3000:80"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=http://libsql:8080
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
    networks:
      - app-network

  migrator:
    profiles: ["dev", "prod"]
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=http://libsql:8080
    command: sh -c "pnpm run db:migrate || echo 'Migration had errors but continuing anyway'"
    depends_on:
      libsql:
        condition: service_started
    networks:
      - app-network

  nginx:
    profiles: ["dev", "prod"]
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - ${APP_SERVICE:-app}
    networks:
      - app-network

  redis:
    profiles: ["dev", "prod"]
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  libsql:
    profiles: ["dev", "prod"]
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    environment:
      - SQLD_NODE=primary
    volumes:
      - libsql_data:/var/lib/sqld
    ports:
      - "8089:8080"
      - "5001:5001"
    networks:
      - app-network

  drizzle-studio:
    profiles: ["dev"]
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4983:4983"
    environment:
      - DATABASE_URL=http://libsql:8080
    command: pnpm drizzle-kit studio --port 4983 --host 0.0.0.0
    depends_on:
      - libsql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  libsql_data:
